server:
  port: 8001
spring:
  application:
    name: system-service
  cloud:
    nacos:
      server-addr: 10.2.64.182:8841
      discovery:
        username: nacos
        password: nacos
        namespace: public