server:
  port: 8011
spring:
  application:
    name: system-service
  datasource:
    url: jdbc:oracle:thin:@10.2.0.171:1521:BSTEST
    username: fc_mes
    password: fc_mes
    driver-class-name: oracle.jdbc.OracleDriver
  cloud:
    nacos:
      server-addr: 10.2.64.182:8841
      discovery:
        username: nacos
        password: nacos
        namespace: public
mybatis-plus:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapping/**/*.xml